# Configuration for Upptime

owner: sashakarcz  # Your GitHub username
repo: uptime       # Your repository name

sites:
  # Standard HTTP Monitoring
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com

  # DNS Monitoring Example
  - name: DNS Check for example.com
    domain: example.com
    expected_record: 93.184.216.34
    record_type: A
    check: "dns"

  - name: DNS Check for example.org
    domain: example.org
    expected_record: mail.example.net
    record_type: CNAME
    check: "dns"

status-website:
  cname: dns-monitor.sashakarcz.com
  name: DNS Monitoring Status
  introTitle: "**DNS Monitoring Status Page**"
  introMessage: This page shows the real-time status of our DNS and service monitoring.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/sashakarcz/uptime
