# Configuration for Upptime

owner: sashakarcz  # Your GitHub username
repo: uptime       # Your repository name

sites:
  # URL-based and DNS-based checks combined
  - name: Google
    url: https://www.google.com

  - name: Wikipedia
    url: https://en.wikipedia.org

  - name: Hacker News
    url: https://news.ycombinator.com

  - name: Example
    url: https://example.com
    dns:
      domain: example.com
      expected_record:
        - 93.184.216.34
      record_type: A

  - name: Test Site
    url: https://test.com
    dns:
      domain: test.com
      expected_record:
        - 192.0.2.1
      record_type: A

  - name: Mail Example
    dns:
      domain: mail.example.com
      expected_record:
        - mail.example.net
      record_type: CNAME

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: DNS
      href: /history/dns_status.md
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
