domains:
  - domain: 'example.com'
    expected_record: '93.184.216.34'
    record_type: 'A'
  - domain: 'test.com'
    expected_record: '192.0.2.1'
    record_type: 'A'
  - domain: 'mail.example.com'
    expected_record: 'mail.example.net'
    record_type: 'CNAME'
